# Copyright 2021 Gnosis Ltd.
# SPDX-License-Identifier: Apache-2.0

[workspace]
resolver = "2"
members = [
    "crates/*",
    "tools/*",
    "bin/*"]
default-members = ["bin/reth", "crates/*", "bin/*"]