# Copyright 2021 Gnosis Ltd.
# SPDX-License-Identifier: Apache-2.0

tab_spaces = 2
edition = "2018"
fn_single_line = true
format_code_in_doc_comments = true
format_strings = true
imports_layout = "HorizontalVertical"
imports_granularity = "Crate"
normalize_comments = true
normalize_doc_attributes = true
reorder_impl_items = true
group_imports = "StdExternalCrate"
use_try_shorthand = true
wrap_comments = true
